version: '3.9'

services:
  node_app:
    container_name: node_app
    build: .
    image: dalmendras/node_live_app
    ports:
      - "3000:3000"
    environment:
      - SERVER_PORT=3000
      - DB_USER=postgres
      - DB_PASSWORD=david
      - DB_HOST=node_db
      - DB_NAME=de
      - DB_PORT=5432
      - API_USER_MASTER=admin@admin.com
      - API_PASS_MASTER=password
    depends_on:
      - node_db
    volumes:
      - ./uploads:/app/uploads  # Add this line
      - .:/app
    restart: always
  node_db:
    container_name: node_db
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=david
      - POSTGRES_DB=de
    volumes:
      - node_db_data:/var/lib/postgresql/data
      - .:/app

volumes:
  node_db_data: {}